### ISSUE TITLE
No maven repository available anymore

### ISSUE THREAD

**Issue by sweiler** [uwol/proleap-cobol-parser#70]
Hello there,

we're using this library and were also using this maven.proleap.io repository. As the latest commit suggests (0a9a7e1) and as we see it, this repository is no longer available. Are there any plans to make this library available on the official maven repositories? Or is there another way to use this library with maven, besides building it from sources by ourselves and hosting it in our own maven repository?

Thank you for your support!

**Comment by uwol** [comment]
Hi Simon, 

correct, we had to switch our hosting to a cloud provider and in that context lost FTP support, which is required for deployment with Apache Maven Wagon FTP. Due to time constraints we could not implement another solution such as e.g. Maven Central Repository, yet.

So right now, building from sources and hosting in your company maven repository would be the best solution, until we develop a solution on our side.

Besides: We feel honored that ThoughtWorks is using ProLeap COBOL parser. If there is interest in additional features or dialects for the parser, or if there are ideas for further development and applications, please let us know!

Best regards
Ulrich

**Comment by sweiler** [comment]
Hi Ulrich,
thank you for your quick response!
Okay, so then we'll use our own maven repository for now. If you need any support in setting up the Maven Central solution, I'm happy to assist.

To your besides note, thank you very much for offering support, but currently we're more or less just playing around with this :D

- Simon
